name = "coast-fi-calculator"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "coast-fi-calculator"
compatibility_date = "2024-01-01"

[[env.production.routes]]
pattern = "*"
custom_domain = false